
SET SERVEROUTPUT ON SIZE 1000000;

BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE dropout_records PURGE';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE != -942 THEN
      RAISE;
    END IF;
END;
/

CREATE TABLE dropout_records (
  student_id NUMBER GENERATED BY DEFAULT AS IDENTITY,
  student_name VARCHAR2(200),
  age NUMBER(3),
  sex CHAR(1),
  grade_level VARCHAR2(50),
  district VARCHAR2(10),
  dropout_reason VARCHAR2(400),
  last_attendance_date DATE,
  est_annual_loss NUMBER(10,2),
  notes VARCHAR2(1000),
  CONSTRAINT dr_pk PRIMARY KEY (student_id)
);

PROMPT Table dropout_records created.
